sources:
  - FrancoisOne.glyphs
familyName: "Francoise One"
#buildvariable: "None" Tried: "false", "0"
buildStatic: "true"
# outputDir: "../fonts/"
ttDir: "../fonts/ttf"
otDir: "../fonts/otf"
woffDir: "../fonts/webfonts"



